In [3]:
import sys
sys.path.append('..')

In [2]:
import logging
from pathlib import Path
import shutil
import pandas as pd
import os
from pyedflib import highlevel
import subprocess
from config.paths import PatientDir

In [13]:
old_root = Path('/data/home/webb/UNEEG_data_ultra/')
root = Path('/data/home/webb/original_UNEEG/')
data_dir = root / 'data'

In [10]:
# Make edf dirs a subfolder
for pdir in old_root.iterdir():
    pname = pdir.name
    new_pdir = data_dir / pname
    new_pdir.mkdir(exist_ok=True)
    # the pdir is renamed to edf_data in the correct folder
    pdir.rename(new_pdir / 'edf_data')

In [16]:
# Copy competition training data
src_dir = Path('/data/datasets/20250501_SUBQ_SeizurePredictionCompetition_2025final/TrainingData')
for i in [1, 2, 3]:
    src = src_dir / f'TrainingP{i}'
    dst = data_dir / f'competition-{i}' / src.name
    shutil.copytree(src, dst, copy_function=shutil.copy2)

In [18]:
# make seizure annotation folders
for pdir in data_dir.iterdir():
    anns_original_dir = pdir / 'seizure_annotations' / 'original'
    anns_original_dir.mkdir(exist_ok=True, parents=True)

In [19]:
# move competition data to a single edf folder
for i in [1, 2, 3]:
    pdir = data_dir / f'competition-{i}'
    train_dir = pdir / f'TrainingP{i}'
    test_dir = pdir / f'P{i}Testing'
    edf_dir = pdir/ 'edf_data'
    edf_dir.mkdir(exist_ok=True)

    # Move files from train and test directories
    for src in [train_dir, test_dir]:
        if src.exists():
            for file in src.iterdir():
                if file.is_file():
                    file.rename(edf_dir / file.name)

            # Remove the now empty directory
            try:
                src.rmdir()
            except OSError:
                print(f"Directory not empty or could not be removed: {src}")

In [29]:
# Try loading seizure starts
szr_starts_path = data_dir / 'competition-3' / 'seizure_annotations' / 'original' / 'seizure_starts.csv'
szr_starts = pd.read_csv(szr_starts_path, parse_dates=['start'])
szr_starts

                 start
0  2022-01-29 03:53:11
1  2022-01-30 05:51:19
2  2022-02-13 04:57:23
3  2022-02-13 08:38:09
4  2022-02-27 01:22:07
..                 ...
58 2023-02-10 03:00:43
59 2023-02-20 06:17:29
60 2023-02-25 04:53:23
61 2023-03-13 02:37:01
62 2023-03-14 04:47:18

[63 rows x 1 columns]

In [8]:
# check out duplicated files
os.chdir(data_dir)

'/data/home/webb/original_UNEEG/data'

In [11]:
signals, signal_header, header = highlevel.read_edf("./U002-DE01-16/edf_data/U002-DE01-16_OUTPT_V6_000538_0004003_20000403_03_EEGdata.edf")

In [ ]:
# Delete duplicate files in each patient folder
all_deleted_files = []
pdirs = [PatientDir(p) for p in data_dir.iterdir()]
for pdir in pdirs:
    target_dir = pdir.edf_dir
    logging.info(f'Processing duplicates for {pdir.name}')
    dups = subprocess.run

In [37]:
# correct_competition_ptnt_sequence_file_sequence_number
import re
from config.paths import PATHS, Dataset
import pandas as pd
from pathlib import Path

# for pdir in PATHS.patient_dirs([Dataset.competition]):
pdir = PATHS.patient_dirs([Dataset.competition])[2]
print(pdir.name)
edfs = pd.DataFrame({'path': pdir.edf_dir.iterdir()})

def get_competition_sequence_number(path: Path) -> int:
    """
    Extracts the sequence number from filenames:
    - P1_287.edf -> 287
    - file_794_SQ1317.edf -> 1317
    """
    name = path.stem
    # Try finding SQXXXX first
    sq_match = re.search(r'SQ(\d+)', name)
    if sq_match: return int(sq_match.group(1))
    # Fallback to the last numeric part (e.g., P1_287 -> 287)
    num_match = re.findall(r'\d+', name)
    if num_match: return int(num_match[-1])
    raise ValueError(f"Couldn't extract sequence number from {name}")


edfs['seq'] = edfs['path'].apply(get_competition_sequence_number)
edfs.sort_values(by='seq', inplace=True)
edfs.reset_index(drop=True, inplace=True)

# Check where sequence and index are unequal
unequal_mask = edfs['seq'] != edfs.index
if any(unequal_mask):
    print(edfs[unequal_mask])

# Rename
edfs["filename"] = edfs.apply(
    lambda row: f"{row.path.parent.parent.name}_{row.name:04d}.edf",
    axis=1
)
edfs

competition-3
                                                   path   seq
220   /data/home/webb/original_UNEEG/datasets/compet...   221
221   /data/home/webb/original_UNEEG/datasets/compet...   223
222   /data/home/webb/original_UNEEG/datasets/compet...   225
223   /data/home/webb/original_UNEEG/datasets/compet...   227
224   /data/home/webb/original_UNEEG/datasets/compet...   228
...                                                 ...   ...
1883  /data/home/webb/original_UNEEG/datasets/compet...  1892
1884  /data/home/webb/original_UNEEG/datasets/compet...  1893
1885  /data/home/webb/original_UNEEG/datasets/compet...  1894
1886  /data/home/webb/original_UNEEG/datasets/compet...  1895
1887  /data/home/webb/original_UNEEG/datasets/compet...  1896

[1668 rows x 2 columns]

,path,seq,filename
0,/data/home/webb/original_UNEEG/datasets/compet...,0,competition-3_0000.edf
1,/data/home/webb/original_UNEEG/datasets/compet...,1,competition-3_0001.edf
2,/data/home/webb/original_UNEEG/datasets/compet...,2,competition-3_0002.edf
3,/data/home/webb/original_UNEEG/datasets/compet...,3,competition-3_0003.edf
4,/data/home/webb/original_UNEEG/datasets/compet...,4,competition-3_0004.edf
...,...,...,...
1883,/data/home/webb/original_UNEEG/datasets/compet...,1892,competition-3_1883.edf
1884,/data/home/webb/original_UNEEG/datasets/compet...,1893,competition-3_1884.edf
1885,/data/home/webb/original_UNEEG/datasets/compet...,1894,competition-3_1885.edf
1886,/data/home/webb/original_UNEEG/datasets/compet...,1895,competition-3_1886.edf
1887,/data/home/webb/original_UNEEG/datasets/compet...,1896,competition-3_1887.edf

In [38]:
edfs[unequal_mask]

,path,seq,filename
220,/data/home/webb/original_UNEEG/datasets/compet...,221,competition-3_0220.edf
221,/data/home/webb/original_UNEEG/datasets/compet...,223,competition-3_0221.edf
222,/data/home/webb/original_UNEEG/datasets/compet...,225,competition-3_0222.edf
223,/data/home/webb/original_UNEEG/datasets/compet...,227,competition-3_0223.edf
224,/data/home/webb/original_UNEEG/datasets/compet...,228,competition-3_0224.edf
...,...,...,...
1883,/data/home/webb/original_UNEEG/datasets/compet...,1892,competition-3_1883.edf
1884,/data/home/webb/original_UNEEG/datasets/compet...,1893,competition-3_1884.edf
1885,/data/home/webb/original_UNEEG/datasets/compet...,1894,competition-3_1885.edf
1886,/data/home/webb/original_UNEEG/datasets/compet...,1895,competition-3_1886.edf
1887,/data/home/webb/original_UNEEG/datasets/compet...,1896,competition-3_1887.edf

In [40]:
# Rename
for i, edf in edfs.iterrows():
    new_path = edf.path.parent / edf.filename
    if new_path != edf.path:
        print(new_path)
        edf.path.rename(new_path)

/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0000.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0001.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0002.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0003.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0004.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0005.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0006.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0007.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0008.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0009.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0010.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0011.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0012.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0013.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0014.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0015.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0016.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0017.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0018.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0019.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0020.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0021.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0022.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0023.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0024.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0025.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0026.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0027.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0028.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0029.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0030.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0031.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0032.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0033.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0034.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0035.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0036.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0037.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0038.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0039.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0040.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0041.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0042.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0043.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0044.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0045.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0046.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0047.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0048.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0049.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0050.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0051.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0052.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0053.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0054.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0055.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0056.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0057.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0058.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0059.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0060.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0061.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0062.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0063.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0064.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0065.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0066.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0067.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0068.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0069.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0070.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0071.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0072.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0073.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0074.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0075.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0076.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0077.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0078.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0079.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0080.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0081.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0082.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0083.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0084.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0085.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0086.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0087.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0088.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0089.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0090.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0091.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0092.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0093.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0094.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0095.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0096.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0097.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0098.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0099.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0100.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0101.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0102.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0103.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0104.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0105.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0106.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0107.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0108.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0109.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0110.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0111.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0112.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0113.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0114.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0115.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0116.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0117.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0118.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0119.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0120.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0121.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0122.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0123.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0124.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0125.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0126.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0127.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0128.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0129.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0130.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0131.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0132.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0133.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0134.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0135.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0136.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0137.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0138.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0139.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0140.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0141.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0142.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0143.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0144.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0145.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0146.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0147.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0148.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0149.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0150.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0151.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0152.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0153.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0154.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0155.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0156.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0157.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0158.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0159.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0160.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0161.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0162.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0163.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0164.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0165.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0166.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0167.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0168.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0169.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0170.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0171.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0172.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0173.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0174.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0175.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0176.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0177.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0178.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0179.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0180.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0181.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0182.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0183.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0184.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0185.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0186.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0187.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0188.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0189.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0190.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0191.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0192.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0193.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0194.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0195.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0196.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0197.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0198.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0199.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0200.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0201.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0202.edf
/data/home/webb/original_UNEEG/datasets/competition/competition-3/edf_data/competition-3_0203.edf