In [1]:
import pandas as pd
from pathlib import Path
from config import PATHS
from helpers import rename_patient

In [2]:
# Paths
# on server:
in_path = PATHS.per_patient_comparison_table.pickle  # on server
out_path = Path("~/thesis_data/tables/copes_table.tex").expanduser()

# local:
in_path = Path('~/thesis_files/statistical_results/.per_patient.pkl').expanduser()  # local
out_path = Path('~/Developer/MastersThesis/src/tables/copes_table.tex').expanduser()

In [3]:
comp = pd.read_pickle(in_path)
comp

metric        total_clips        preictal_clips      non_preictal_clips  \
split               train   test          train test              train
patient
competition-1       37987  17444            196  114              37791
competition-2       38019  31223            186  129              37833
competition-3       34757  21520            221  156              34536
U002-DE01-01        26170  28312            691  464              25479
U002-DE01-03        14764  27045            202  106              14562
U002-DE01-04        12334  13039            212  137              12122
U002-DE01-05        22284  20165            239  168              22045
U002-DE01-07         9941   7712             40   36               9901
U002-DE01-12        12865  15328            100   63              12765
U002-DE01-15        18933  24942             77   58              18856
U002-DE01-16        22123   9482             48   48              22075
U002-DE01-17        14106  21158             69   53              14037

metric               preictal_ratio           corr_of_pred_errors
split           test          train      test               train      test
patient
competition-1  17330        0.00516  0.006535            0.853414  0.880122
competition-2  31094       0.004892  0.004132            0.808760  0.739500
competition-3  21364       0.006358  0.007249            0.853980  0.849131
U002-DE01-01   27848       0.026404  0.016389            0.821004  0.822417
U002-DE01-03   26939       0.013682  0.003919            0.671090  0.561897
U002-DE01-04   12902       0.017188  0.010507            0.514272  0.412429
U002-DE01-05   19997       0.010725  0.008331            0.804766  0.812181
U002-DE01-07    7676       0.004024  0.004668            0.854925  0.901007
U002-DE01-12   15265       0.007773   0.00411            0.490606  0.345045
U002-DE01-15   24884       0.004067  0.002325            0.725209  0.762821
U002-DE01-16    9434        0.00217  0.005062            0.695311  0.679250
U002-DE01-17   21105       0.004892  0.002505            0.830183  0.826612

In [23]:
t = comp['corr_of_pred_errors'].copy()
t.index = t.index.map(rename_patient).rename('Patient')
t = t.reset_index(drop=False)
t.columns.name = None
t = t.rename(columns={'train': 'Train', 'test': 'Test'})
t.columns = [r'\textbf{{{}}}'.format(str(c)) for c in t.columns]
t

   \textbf{Patient}  \textbf{Train}  \textbf{Test}
0               C01        0.853414       0.880122
1               C02        0.808760       0.739500
2               C03        0.853980       0.849131
3               U01        0.821004       0.822417
4               U03        0.671090       0.561897
5               U04        0.514272       0.412429
6               U05        0.804766       0.812181
7               U07        0.854925       0.901007
8               U12        0.490606       0.345045
9               U15        0.725209       0.762821
10              U16        0.695311       0.679250
11              U17        0.830183       0.826612

In [24]:
t.to_latex(
    out_path,
    index=False,
    float_format='%.3f'
)